// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace demo_source.@public.person
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Envelope : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"Envelope\",\"namespace\":\"demo_source.public.person\",\"field" +
				"s\":[{\"name\":\"before\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Valu" +
				"e\",\"namespace\":\"demo_source.public.person\",\"fields\":[{\"name\":\"person_id\",\"type\":" +
				"\"int\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"favorite_color\",\"default\":null,\"" +
				"type\":[\"null\",\"string\"]},{\"name\":\"age\",\"default\":null,\"type\":[\"null\",\"int\"]}],\"c" +
				"onnect.name\":\"demo_source.public.person.Value\"}]},{\"name\":\"after\",\"default\":null" +
				",\"type\":[\"null\",\"Value\"]},{\"name\":\"source\",\"type\":{\"type\":\"record\",\"name\":\"Sourc" +
				"e\",\"namespace\":\"io.debezium.connector.postgresql\",\"fields\":[{\"name\":\"version\",\"t" +
				"ype\":\"string\"},{\"name\":\"connector\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"strin" +
				"g\"},{\"name\":\"ts_ms\",\"type\":\"long\"},{\"name\":\"snapshot\",\"default\":\"false\",\"type\":[" +
				"\"string\",\"null\"]},{\"name\":\"db\",\"type\":\"string\"},{\"name\":\"schema\",\"type\":\"string\"" +
				"},{\"name\":\"table\",\"type\":\"string\"},{\"name\":\"txId\",\"default\":null,\"type\":[\"null\"," +
				"\"long\"]},{\"name\":\"lsn\",\"default\":null,\"type\":[\"null\",\"long\"]},{\"name\":\"xmin\",\"de" +
				"fault\":null,\"type\":[\"null\",\"long\"]}],\"connect.name\":\"io.debezium.connector.postg" +
				"resql.Source\"}},{\"name\":\"op\",\"type\":\"string\"},{\"name\":\"ts_ms\",\"default\":null,\"ty" +
				"pe\":[\"null\",\"long\"]},{\"name\":\"transaction\",\"default\":null,\"type\":[\"null\",{\"type\"" +
				":\"record\",\"name\":\"ConnectDefault\",\"namespace\":\"io.confluent.connect.avro\",\"field" +
				"s\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"total_order\",\"type\":\"long\"},{\"name\":\"" +
				"data_collection_order\",\"type\":\"long\"}]}]}],\"connect.name\":\"demo_source.public.pe" +
				"rson.Envelope\"}");
		private demo_source.@public.person.Value _before;
		private demo_source.@public.person.Value _after;
		private io.debezium.connector.postgresql.Source _source;
		private string _op;
		private System.Nullable<long> _ts_ms;
		private io.confluent.connect.avro.ConnectDefault _transaction;
		public virtual Schema Schema
		{
			get
			{
				return Envelope._SCHEMA;
			}
		}
		public demo_source.@public.person.Value before
		{
			get
			{
				return this._before;
			}
			set
			{
				this._before = value;
			}
		}
		public demo_source.@public.person.Value after
		{
			get
			{
				return this._after;
			}
			set
			{
				this._after = value;
			}
		}
		public io.debezium.connector.postgresql.Source source
		{
			get
			{
				return this._source;
			}
			set
			{
				this._source = value;
			}
		}
		public string op
		{
			get
			{
				return this._op;
			}
			set
			{
				this._op = value;
			}
		}
		public System.Nullable<long> ts_ms
		{
			get
			{
				return this._ts_ms;
			}
			set
			{
				this._ts_ms = value;
			}
		}
		public io.confluent.connect.avro.ConnectDefault transaction
		{
			get
			{
				return this._transaction;
			}
			set
			{
				this._transaction = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.before;
			case 1: return this.after;
			case 2: return this.source;
			case 3: return this.op;
			case 4: return this.ts_ms;
			case 5: return this.transaction;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.before = (demo_source.@public.person.Value)fieldValue; break;
			case 1: this.after = (demo_source.@public.person.Value)fieldValue; break;
			case 2: this.source = (io.debezium.connector.postgresql.Source)fieldValue; break;
			case 3: this.op = (System.String)fieldValue; break;
			case 4: this.ts_ms = (System.Nullable<long>)fieldValue; break;
			case 5: this.transaction = (io.confluent.connect.avro.ConnectDefault)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
