// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace demo_source.@public.person
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Key : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"Key\",\"namespace\":\"demo_source.public.person\",\"fields\":[{" +
				"\"name\":\"person_id\",\"type\":\"int\"}],\"connect.name\":\"demo_source.public.person.Key\"" +
				"}");
		private int _person_id;
		public virtual Schema Schema
		{
			get
			{
				return Key._SCHEMA;
			}
		}
		public int person_id
		{
			get
			{
				return this._person_id;
			}
			set
			{
				this._person_id = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.person_id;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.person_id = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
