// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace demo_source.@public.person
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Value : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""Value"",""namespace"":""demo_source.public.person"",""fields"":[{""name"":""person_id"",""type"":""int""},{""name"":""name"",""type"":""string""},{""name"":""favorite_color"",""default"":null,""type"":[""null"",""string""]},{""name"":""age"",""default"":null,""type"":[""null"",""int""]}],""connect.name"":""demo_source.public.person.Value""}");
		private int _person_id;
		private string _name;
		private string _favorite_color;
		private System.Nullable<int> _age;
		public virtual Schema Schema
		{
			get
			{
				return Value._SCHEMA;
			}
		}
		public int person_id
		{
			get
			{
				return this._person_id;
			}
			set
			{
				this._person_id = value;
			}
		}
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		public string favorite_color
		{
			get
			{
				return this._favorite_color;
			}
			set
			{
				this._favorite_color = value;
			}
		}
		public System.Nullable<int> age
		{
			get
			{
				return this._age;
			}
			set
			{
				this._age = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.person_id;
			case 1: return this.name;
			case 2: return this.favorite_color;
			case 3: return this.age;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.person_id = (System.Int32)fieldValue; break;
			case 1: this.name = (System.String)fieldValue; break;
			case 2: this.favorite_color = (System.String)fieldValue; break;
			case 3: this.age = (System.Nullable<int>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
