// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace io.debezium.connector.postgresql
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Source : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""Source"",""namespace"":""io.debezium.connector.postgresql"",""fields"":[{""name"":""version"",""type"":""string""},{""name"":""connector"",""type"":""string""},{""name"":""name"",""type"":""string""},{""name"":""ts_ms"",""type"":""long""},{""name"":""snapshot"",""default"":""false"",""type"":[""string"",""null""]},{""name"":""db"",""type"":""string""},{""name"":""schema"",""type"":""string""},{""name"":""table"",""type"":""string""},{""name"":""txId"",""default"":null,""type"":[""null"",""long""]},{""name"":""lsn"",""default"":null,""type"":[""null"",""long""]},{""name"":""xmin"",""default"":null,""type"":[""null"",""long""]}],""connect.name"":""io.debezium.connector.postgresql.Source""}");
		private string _version;
		private string _connector;
		private string _name;
		private long _ts_ms;
		private string _snapshot;
		private string _db;
		private string _schema;
		private string _table;
		private System.Nullable<long> _txId;
		private System.Nullable<long> _lsn;
		private System.Nullable<long> _xmin;
		public virtual Schema Schema
		{
			get
			{
				return Source._SCHEMA;
			}
		}
		public string version
		{
			get
			{
				return this._version;
			}
			set
			{
				this._version = value;
			}
		}
		public string connector
		{
			get
			{
				return this._connector;
			}
			set
			{
				this._connector = value;
			}
		}
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		public long ts_ms
		{
			get
			{
				return this._ts_ms;
			}
			set
			{
				this._ts_ms = value;
			}
		}
		public string snapshot
		{
			get
			{
				return this._snapshot;
			}
			set
			{
				this._snapshot = value;
			}
		}
		public string db
		{
			get
			{
				return this._db;
			}
			set
			{
				this._db = value;
			}
		}
		public string schema
		{
			get
			{
				return this._schema;
			}
			set
			{
				this._schema = value;
			}
		}
		public string table
		{
			get
			{
				return this._table;
			}
			set
			{
				this._table = value;
			}
		}
		public System.Nullable<long> txId
		{
			get
			{
				return this._txId;
			}
			set
			{
				this._txId = value;
			}
		}
		public System.Nullable<long> lsn
		{
			get
			{
				return this._lsn;
			}
			set
			{
				this._lsn = value;
			}
		}
		public System.Nullable<long> xmin
		{
			get
			{
				return this._xmin;
			}
			set
			{
				this._xmin = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.version;
			case 1: return this.connector;
			case 2: return this.name;
			case 3: return this.ts_ms;
			case 4: return this.snapshot;
			case 5: return this.db;
			case 6: return this.schema;
			case 7: return this.table;
			case 8: return this.txId;
			case 9: return this.lsn;
			case 10: return this.xmin;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.version = (System.String)fieldValue; break;
			case 1: this.connector = (System.String)fieldValue; break;
			case 2: this.name = (System.String)fieldValue; break;
			case 3: this.ts_ms = (System.Int64)fieldValue; break;
			case 4: this.snapshot = (System.String)fieldValue; break;
			case 5: this.db = (System.String)fieldValue; break;
			case 6: this.schema = (System.String)fieldValue; break;
			case 7: this.table = (System.String)fieldValue; break;
			case 8: this.txId = (System.Nullable<long>)fieldValue; break;
			case 9: this.lsn = (System.Nullable<long>)fieldValue; break;
			case 10: this.xmin = (System.Nullable<long>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
